Update test-deploy_unimofot.yml

diff --git a/.github/workflows/test-deploy_unimofot.yml b/.github/workflows/test-deploy_unimofot.yml
--- a/.github/workflows/test-deploy_unimofot.yml
+++ b/.github/workflows/test-deploy_unimofot.yml
@@ -19,7 +19,7 @@ jobs:
           node-version: '20.x'
 
       - name: Install dependencies
-        run: npm ci
+        run: npm install
 
       - name: Build the project
         run: npm run build
@@ -46,6 +46,12 @@ jobs:
         with:
           name: node-app
 
+      - name: List files after download
+        run: ls -la
+
+      - name: Check if build folder exists
+        run: if [ -d "build" ]; then echo "Build folder exists"; else echo "Build folder not found" && exit 1; fi
+
       - name: Zip build folder
         run: zip -r build.zip build
 
@@ -57,7 +63,3 @@ jobs:
           slot-name: 'Production'
           package: build.zip
           publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_079C5DC90F9946F1A135B9D0A1A0311C }}
-
-
-
-          
